# Generated by Django 3.2.2 on 2021-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0008_auto_20210515_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_customer',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
