# Generated by Django 3.2.2 on 2021-05-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0011_alter_contact_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_customer',
            new_name='email',
        ),
    ]
