# Generated by Django 3.2.2 on 2023-10-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0012_rename_email_customer_contact_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings',
            new_name='web_settings',
        ),
    ]
