# Generated by Django 3.2.2 on 2021-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0006_auto_20210514_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
