# Generated by Django 3.2.2 on 2021-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0010_rename_message_contact_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messages',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
